### ISSUE TITLE
PHP 7.4 compliancy

### ISSUE THREAD

**Issue by leiluspocus** [ellumilel/php-excel-writer#8]
Hello,

I'm using your library on a PHP 7.4 application. 

I have the following warning:
`[2020-06-01 12:48:47] request.CRITICAL: Uncaught PHP Exception Behat\Testwork\Call\Exception\CallErrorException: "8192: Array and string offset access syntax with curly braces is deprecated in /www/vendor/ellumilel/php-excel-writer/src/Xl/Worksheets/SheetXml.php line 198" at /www/vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php line 90 {"exception":"[object] (Behat\\Testwork\\Call\\Exception\\CallErrorException(code: 0): 8192: Array and string offset access syntax with curly braces is deprecated in /www/vendor/ellumilel/php-excel-writer/src/Xl/Worksheets/SheetXml.php line 198 at /www/vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php:90)","reportLocation":`

Can I make a small change on the `src/Xl/Worksheets/SheetXml.php` file and replace all the `$value{0}` with `$value[0]` as suggested [here](https://stackoverflow.com/questions/59158548/array-and-string-offset-access-syntax-with-curly-braces-is-deprecated) ?

**Comment by leiluspocus** [comment]
I've cloned the repository, I can open a pull request if you add me as a contributor to the project.

**Comment by ellumilel** [comment]
Hello,

https://github.com/ellumilel/php-excel-writer/pull/6
